### ISSUE TITLE
congratulations on remaking a feature that is already in gmod

### ISSUE THREAD

**Issue by win32kbase** [GlorifiedPig/gmod-i18n#1]
https://wiki.facepunch.com/gmod/language.Add
https://wiki.facepunch.com/gmod/language.GetPhrase

**Comment by GlorifiedPig** [comment]
you realize that's different, right ?

**Comment by win32kbase** [comment]
what's the point when you can just add the language in to the string and parse it..? still pointless

**Comment by GlorifiedPig** [comment]
> 
> 
> what's the point when you can just add the language in to the string and parse it..? still pointless

me wondering when you are going to jump off my dick:

**Comment by win32kbase** [comment]
someone sent it to me mate it was funny

**Comment by WilliamVenner** [comment]
The gmod language library doesn't even have a way to split up phrases into different languages

It doesn't even have a way of listening to language changes other than a cvar change callback

**Comment by TomDotBat** [comment]
Congratulations on making a feature that isn't already in gmod 🙌

**Comment by owojcikiewicz** [comment]
what's the point of even opening this issue? it's clearly not the same functionality

**Comment by Vadmeme** [comment]
me when i remake epic gmod function because im out of shit to do
[GlorifiedOptimizations.zip](https://github.com/GlorifiedPig/gmod-i18n/files/4512362/GlorifiedOptimizations.zip)

**Comment by win32kbase** [comment]
hows the $100 anti alt comin mate

**Comment by Vadmeme** [comment]
me when 2 file.time checks is worth $100

**Comment by WilliamVenner** [comment]
me when my only talent is sociopathically ruining other people's fun in the pursuit of profits

**Comment by Vadmeme** [comment]
nigga i called you for blogs support and you didnt answer like a little bitch

**Comment by Vadmeme** [comment]
XeonDRM is worse than glorified drm and thats something to be ashamed of

**Comment by Vadmeme** [comment]
it took me

20 fucking minutes to crack it and this includes downloading it and going to get a bagel

**Comment by WilliamVenner** [comment]
> he cracked a soft lua DRM

![](https://i.imgur.com/EAUhEq5.jpg)

**Comment by Vadmeme** [comment]
well you kinda rage ignored my phone call so like, rude?
![billycucked](https://user-images.githubusercontent.com/32437728/79910551-c84c4080-83d3-11ea-8d6f-97840afdec04.png)

**Comment by GlorifiedPig** [comment]
> 
> 
> hows the $100 anti alt comin mate

pretty good, made more money than meth in the first 2 days of release lol

**Comment by Vadmeme** [comment]
DO ***NOT*** CHANGE THE ADDON NAME FROM gaa TO ABSOLUTELY ANYTHING ELSE!
DRAG AND DROP THE ADDONS FOLDER INTO YOUR GMOD SERVER'S DIRECTORY AND DON'T FUCK WITH THE INSTALLATION ***ANY*** OTHER WAY!
I AM WARNING YOU

**Comment by BmanGames024** [comment]
So does this entitle us to a refund

**Comment by Vadmeme** [comment]
![glorifiedno](https://user-images.githubusercontent.com/32437728/79912536-072fc580-83d7-11ea-8cbc-9e8dd135f8ab.png)

**Comment by owojcikiewicz** [comment]
why the fuck would you even care, I don't get it

**Comment by owojcikiewicz** [comment]
if he makes shit anti-cheats/drms/anti-alts then that's really his business, why tf would u care

**Comment by Vadmeme** [comment]
well it seems baby cant handle someone having his code

**Comment by owojcikiewicz** [comment]
again, why would you care?

**Comment by BmanGames024** [comment]
lol

**Comment by Vadmeme** [comment]
![yacodinggac](https://user-images.githubusercontent.com/32437728/79912862-8f15cf80-83d7-11ea-9ebf-8518fda31f24.png)

**Comment by owojcikiewicz** [comment]
ok

**Comment by GlorifiedPig** [comment]
> 
> 
> well it seems baby cant handle someone having his code

if by "cant handle" you mean "ignoring" then damn i suck at handling
and you only sent a .txt file send the full .zip of the whole non drm'd code and ill see

**Comment by Vadmeme** [comment]
`
GlorifiedAntiAlt.FileTimeLoaded = GlorifiedAntiAlt.FileTimeLoaded or false
if GlorifiedAntiAlt.FileTimeLoaded == true then return end
GlorifiedAntiAlt.FileTimeLoaded = true

util.AddNetworkString( "GAA.FTCR" )

GlorifiedAntiAlt.RegisterDetection( 102, "file.Time found similarities with Awesomium.dll" )
GlorifiedAntiAlt.RegisterDetection( 103, "file.Time found similarities with platform_misc_000.vpk" )

GlorifiedAntiAlt.CachedVarsNeeded = GlorifiedAntiAlt.CachedVarsNeeded + 2

net.Receive( "GAA.FTCR", function( len, ply )
    local fileTimeTable = net.ReadTable()
    GlorifiedAntiAlt.AddToCache( ply, "AwesomiumTime", fileTimeTable[1] )
    GlorifiedAntiAlt.AddToCache( ply, "PlatformTime", fileTimeTable[2] )
end )

hook.Add( "GlorifiedAntiAlt.DetectionCacheUpdated", "GAA.FileTimeChecks.DetectionCacheUpdated", function( ply )
    GlorifiedAntiAlt.SQLQuery( "SELECT * FROM gaa_data", function( queryResult )
        GlorifiedAntiAlt.SQLQuery( "SELECT * FROM gaa_data WHERE SteamID64 = '" .. ply:SteamID64() .. "' LIMIT 1", function( mainAccount )
            mainAccount = mainAccount[1]
            local awesomiumAlts = 0
            local platformAlts = 0
            local mainDataTable = util.JSONToTable( mainAccount["Data"] )
            PrintTable(queryResult)
            for k, v in pairs( queryResult ) do
                local dataTbl = util.JSONToTable( v["Data"] )
                if v["SteamID64"] == mainAccount["SteamID64"] then continue end
                if dataTbl["AwesomiumTime"] == mainDataTable["AwesomiumTime"] then awesomiumAlts = awesomiumAlts + 1 end
                if dataTbl["PlatformTime"] == mainDataTable["PlatformTime"] then platformAlts = platformAlts + 1 end
            end
            if awesomiumAlts > 0 then 
                GlorifiedAntiAlt.AddDetection( ply, 102, awesomiumAlts )
            end
            if platformAlts > 0 then 
                GlorifiedAntiAlt.AddDetection( ply, 103, platformAlts )
            end
        end )
    end )
end )
`

nice drm, didnt even change encryption key (28)

**Comment by Vadmeme** [comment]
![epiconeglori](https://user-images.githubusercontent.com/32437728/79914006-5ecf3080-83d9-11ea-94a2-fa33cef9e7e8.png)
ah yes the good ol `send the full .zip of the whole non drm'd code and ill see` and then deleting it right after

**Comment by owojcikiewicz** [comment]
i don't get it tho, why spend your time on cracking someone's drm and ruining their business?

**Comment by Vadmeme** [comment]
because its funny

**Comment by NoSharp** [comment]
Oh god. @IAmWolfie What's the point of you commenting here?

**Comment by patrickratzow** [comment]
What's the point of this issue, the functionality isn't even the same. Just a stupid issue

**Comment by WilliamVenner** [comment]
@SaturdaysHeroes https://en.wikipedia.org/wiki/Child_neglect

**Comment by NoSharp** [comment]
What's the point of anyone commenting here?
It's almost as if @GlorifiedPig is doing what he want's on his github!

**Comment by owojcikiewicz** [comment]
it's kinda sad that you literally do not have anything better to do

**Comment by owojcikiewicz** [comment]
> What's the point of this issue, the functionality isn't even the same. Just a stupid issue

this isn't about the repo, it's just a vendetta against pig (for some odd reason)

**Comment by GlorifiedPig** [comment]
> 
> 
> ![epiconeglori](https://user-images.githubusercontent.com/32437728/79914006-5ecf3080-83d9-11ea-94a2-fa33cef9e7e8.png)
> ah yes the good ol `send the full .zip of the whole non drm'd code and ill see` and then deleting it right after

it was obviously just for the DMCA request lol

**Comment by Vadmeme** [comment]
ah yes the classic `i was only pretending to be retarded`

**Comment by NoSharp** [comment]
@GlorifiedPig Just close this issue it's just become a cesspool.

**Comment by TomDotBat** [comment]
> @GlorifiedPig Just close this issue it's just become a cesspool.

Please do

**Comment by RealDashU** [comment]
sex

**Comment by WilliamVenner** [comment]
sneed

**Comment by RealDashU** [comment]
https://user-images.githubusercontent.com/74258248/105818346-cdeb3e00-5f84-11eb-9f99-1bca489cee32.mp4
